In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv("heart (1).csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [4]:
X=df.drop('target',axis=1)
y=df['target']

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [28]:
svm_linear=SVC(kernel='linear',C=1)
svm_linear.fit(X_train,y_train)
y_pred_linear=svm_linear.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy Score:",accuracy_score(y_pred_linear,y_test))

Accuracy Score: 0.8146341463414634


In [30]:
confusion_matrix(y_pred_linear,y_test)

array([[72,  8],
       [30, 95]])

In [31]:
svm_poly=SVC(kernel='poly',degree=3,C=1)
svm_poly.fit(X_train,y_train)
y_pred_poly=svm_poly.predict(X_test)
print("Accuracy:",accuracy_score(y_pred_poly,y_test))
confusion_matrix(y_pred_poly,y_test)

Accuracy: 0.9073170731707317


array([[ 85,   2],
       [ 17, 101]])

In [32]:
svm_rbf=SVC(kernel='rbf',C=1,gamma='scale')
svm_rbf.fit(X_train,y_train)
y_pred_rbf=svm_rbf.predict(X_test)
print("Accuracy:",accuracy_score(y_pred_rbf,y_test))
confusion_matrix(y_pred_rbf,y_test)

Accuracy: 0.8878048780487805


array([[85,  6],
       [17, 97]])